# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sidneyssantos
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  architecture: arm64
  timeout: 20
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  individually: true

# esbuild
build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          method: POST
          path: /signin

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          method: POST
          path: /signup

  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          method: GET
          path: /me
